[package]
name = "fuzz_read"
version = "0.1.0"
edition = "2021"

[dependencies]
afl = "0.15.10"
replace_with = "0.1.7"
tikv-jemallocator = "0.6.0"

[dependencies.zip]
path = ".."
default-features = false

[features]
zip-default = ["zip/default"]

[workspace]
