name: Cargo hack

permissions:
  contents: read

concurrency:
  group: cargo-hack-${{ (github.ref == 'refs/heads/master' && github.sha) || (github.event_name == 'pull_request' && github.head_ref) || github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  pull_request:

# this file is used to test all feature combinations using cargo-hack
# but only specific conditions to avoid overloading CI on every push/PR
# since this CI takes a very long time

jobs:
  cargo-hack-all-features:
    if: |
      startsWith(github.base_ref, 'release-plz-') ||
      contains(join(github.event.pull_request.changed_files, ','), '.github/workflows/cargo_hack.yml')
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: target
          key: ${{ runner.os }}-rust-cargo-hack-${{ hashFiles('Cargo.toml') }}
      - run: cargo hack test --feature-powerset --all-targets --exclude-features _bzip2_any,_arbitrary,_deflate-any
