name: Check typos

permissions:
  contents: read

concurrency:
  group: typos-${{ (github.ref == 'refs/heads/master' && github.sha) || (github.event_name == 'pull_request' && github.head_ref) || github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            release-assets.githubusercontent.com:443
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"
          persist-credentials: false
      - name: typos-action
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # v1.50.1

