name: Check typos

permissions:
  contents: read

concurrency:
  group: typos-${{ (github.ref == 'refs/heads/master' && github.sha) || (github.event_name == 'pull_request' && github.head_ref) || github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            release-assets.githubusercontent.com:443
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: "true"
          persist-credentials: false
      - name: typos-action
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0

