name: Check typos

permissions:
  contents: read

concurrency:
  group: typos-${{ (github.ref == 'refs/heads/master' && github.sha) || (github.event_name == 'pull_request' && github.head_ref) || github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            release-assets.githubusercontent.com:443
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"
          persist-credentials: false
      - name: typos-action
        uses: crate-ci/typos@a8168dc2984a9e2352f183ffe788f0f23a300389 # v1.49.1

